// Generated by CoffeeScript 1.7.1
(function() {
  var to5;

  to5 = require("6to5");

  module.exports = function(grunt) {
    grunt.registerMultiTask("6to5", "Transpile ES6 to ES5", function() {
      var options;
      options = this.options();
      return this.files.forEach(function(el) {
        var res;
        options.filename = el.src[0];
        options.filenameRelative = el.src[0].replace("src/", "");
        res = to5.transformFileSync(el.src[0], options);
        grunt.file.write(el.dest, res.code);
        if (res.map) {
          return grunt.file.write(el.dest + ".map", JSON.stringify(res.map));
        }
      });
    });
    return {
      options: {
        blacklist: ["useStrict"]
      },
      browser: {
        options: {
          modules: "amd",
          amdModuleIds: true,
          runtime: "polyfill"
        },
        files: [
          {
            expand: true,
            cwd: "src",
            src: "**/**/*.js",
            dest: "tmp"
          }
        ]
      },
      node: {
        options: {
          modules: "common"
        },
        files: [
          {
            expand: true,
            cwd: "src",
            src: "**/**/*.js",
            dest: "dist/cmj"
          }
        ]
      }
    };
  };

}).call(this);
