// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    test: {
      src: ['test/*.html'],
      options: {
        run: true,
        reporter: 'Spec',
        log: true,
        timeout: 10000,
        mocha: {
          ignoreLeaks: false
        }
      }
    }
  };

}).call(this);
