// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    options: {
      livereload: true
    },
    js: {
      files: ['src/**/**/*.js'],
      tasks: ['jshint']
    },
    test: {
      files: ['test/**/*.js'],
      tasks: ['mocha']
    }
  };

}).call(this);
